trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  targetRepository: echo "${$(Build.Repository.Name)/Knotx\//}"
  # knotx-data-bridge

steps:
  - script: |
      git clone https://github.com/Knotx/knotx-aggregator.git
      mkdir knotx-repos
    displayName: "Prepare Aggregator"
  - task: CmdLine@2
    inputs:
      script: |
        cd knotx-aggregator/development
        if [[ -z "$(System.PullRequest.SourceBranch)" ]] ; then
          ./pull-all.sh -r ../../knotx-repos -b "$(Build.SourceBranchName)" -a
        else
          ./pull-all.sh -r ../../knotx-repos -b $(System.PullRequest.SourceBranch) -a
        fi
    displayName: "Clone all repositories"
  - task: CmdLine@2
    inputs:
      script: |
        cd knotx-aggregator/development
        ./build-stack.sh -r ../../knotx-repos
    displayName: "Build Stack"
  - task: Maven@3
    inputs:
      mavenPomFile: 'knotx-repos/knotx-docker/pom.xml'
      goals: 'package'
    displayName: "Build Docker image"
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'knotx-repos/knotx-starter-kit/gradlew'
      workingDirectory: 'knotx-repos/knotx-starter-kit'
      tasks: 'build'
    displayName: "Build Starter Kit"
  - script: |
      knotx-repos/$(targetRepository)/gradlew -p knotx-repos/$(targetRepository) clean test jacocoTestReport
      bash <(curl -s https://codecov.io/bash) -s knotx-repos/$(targetRepository) -t $(CODECOV_TOKEN)
      echo $(Build.Repository.Name)
      echo $(Build.Repository.ID)
    displayName: "Run Codecov inspection"