trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      git clone https://github.com/Knotx/knotx-aggregator.git
      mkdir knotx-repos
    displayName: "Prepare Aggregator"
  - task: CmdLine@2
    inputs:
      script: |
        cd knotx-aggregator/development
        if [[ -z "$(System.PullRequest.SourceBranch)" ]] ; then
          ./pull-all.sh -r ../../knotx-repos -b "$(Build.SourceBranchName)" -a
        else
          ./pull-all.sh -r ../../knotx-repos -b $(System.PullRequest.SourceBranch) -a
        fi
    displayName: "Clone all repositories"
  - task: CmdLine@2
    inputs:
      script: |
        cd knotx-aggregator/development
        ./build-stack.sh -r ../../knotx-repos
    displayName: "Build Stack"
  - script: mvn -f knotx-repos/knotx-docker/pom.xml clean package
    displayName: "Build Docker image"
  - script: knotx-repos/knotx-starter-kit/gradlew -p knotx-repos/knotx-starter-kit build
    displayName: "Build Starter Kit"
  - script: |
      knotx-repos/knotx-data-bridge/gradlew -p knotx-repos/knotx-data-bridge clean test jacocoTestReport --rerun-tasks
      bash <(curl -s https://codecov.io/bash) -s knotx-repos/knotx-data-bridge -t $(CODECOV_TOKEN)
    displayName: "Run Codecov inspection"